MAX_RESUME_SIZE = 5

ALLOWED_RESUME_TYPES = ["application/pdf"]

DEFAULT_INTERVIEW_QUESTION_COUNT = 5
MIN_INTERVIEW_QUESTIONS = 3
MAX_INTERVIEW_QUESTIONS = 10

VALID_QUESTION_CATEGORIES = {"technical", "behavioral", "system_design"}
VALID_QUESTION_DIFFICULTIES = {"easy", "medium", "hard"}
DEFAULT_QUESTION_CATEGORY = "technical"
DEFAULT_QUESTION_DIFFICULTY = "medium"